export const TRAIN_ERROR = "TRAIN_ERROR";
export const TRAIN_CLEAR_ERROR = "TRAIN_CLEAR_ERROR";
export const TRAIN_LOADING_LIST = "TRAIN_LOADING_LIST";
export const TRAIN_SET_DATA = "TRAIN_SET_DATA";

export const TRAIN_GET_TRAINED_LIST = "TRAIN_GET_TRAINED_LIST";

export const TRAIN_GET_ALGO_LIST = "TRAIN_GET_ALGO_LIST";
export const TRAIN_RESET_DATA = "TRAIN_RESET_DATA";

export const TRAIN_UPLOAD_LIST = "TRAIN_UPLOAD_LIST";
export const TRAIN_UPLOAD_DATA = "TRAIN_UPLOAD_DATA";
export const TRAIN_DATASET_ANALYSIS = "TRAIN_DATASET_ANALYSIS";

export const TRAIN_SET_NEW_MODEL = "TRAIN_SET_NEW_MODEL";

export const TRAIN_SUGGEST_ALGO = "TRAIN_SUGGEST_ALGO";

export const TRAIN_CLEAR_NEW_MODEL = "TRAIN_CLEAR_NEW_MODEL";

export const TRAIN_PREDICT_DATA = "TRAIN_PREDICT_DATA";
